backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/pdfs/articles"
public_folder: "/assets/pdfs/articles"

collections:
  - label: "Articles"
    name: "articles"
    files:
      - label: "American Match Safes"
        name: "american_section"
        file: "_data/articletest.json"        
        fields: 
          - label: "Gorham articles"
            name: "gorham"
            widget: "string"            
      - label: "European Match Safes (Vestas)"
        name: "european_section"
        file: "_data/articletest.json"        
        fields: 
          - label: "United Kingdom articles"
            name: "uk"
            widget: "string"