backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/pdfs/articles"
public_folder: "/assets/pdfs/articles"

collections:
  - label: "Articles"
    name: "articles"
    files:
      - label: "American Match Safes"
        name: "american_section"
        file: "_data/american.json"        
        fields: 
          - label: "Gorham articles"
            name: "gorham"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
          - label: "Tiffany articles"
            name: "tiffany"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
          - label: "Other articles"
            name: "other"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
      - label: "European Match Safes (Vestas)"
        name: "european_section"
        file: "_data/european.json"        
        fields: 
          - label: "United Kingdom articles"
            name: "uk"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
          - label: "Russia articles"
            name: "russia"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
          - label: "France articles"
            name: "france"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
          - label: "Spain articles"
            name: "spain"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
      - label: "Japanese Match Safes"
        name: "japanese_section"
        file: "_data/japanese.json"        
        fields: 
          - label: "Japanese articles"
            name: "japanese"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
      - label: "Global Match Safes"
        name: "global_section"
        file: "_data/global.json"       
        fields: 
          - label: "Global articles"
            name: "global"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
      - label: "Match Holders"
        name: "holder_section"
        file: "_data/holders.json"     
        fields: 
          - label: "Match Holder articles"
            name: "holder"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
